global:
  smtp_smarthost: '${SMTP_SMARTHOST}'
  smtp_from: '${SMTP_FROM}'
  smtp_auth_username: '${SMTP_AUTH_USERNAME}'
  smtp_auth_password: '${SMTP_AUTH_PASSWORD}'

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'mail_and_sms'

  routes:
    - match:
        alert_type: 'ip_threat'
      receiver: 'ip_threats_discord'
      group_by: ['alertname']
      repeat_interval: 12h
      group_wait: 30s
      group_interval: 20m

receivers:
  - name: 'mail_and_sms'
    email_configs:
      - to: '${SMTP_FROM}'
        send_resolved: true
        require_tls: true
    webhook_configs:
      - url: 'http://web_app:5000/sms_alert'
        send_resolved: true
        http_config:
          bearer_token: '${API_SECRET_TOKEN}'

  - name: 'ip_threats_discord'
    webhook_configs:
      - url: '${DISCORD_IP}'
        send_resolved: true