http:
  middlewares:
    error-pages:
      errors:
        status:
          - "403"
        service: dummy-error
        query: "/403.html"

    geoblock-france:
      plugin:
        geoblock:
          allowLocalRequests: true
          logLocalRequests: false
          logAllowedRequests: false
          logApiRequests: true
          api: "https://get.geojs.io/v1/ip/country/{ip}"
          apiTimeoutMs: 1000
          cacheSize: 20
          forceMonthlyUpdate: true
          allowUnknownCountries: false
          unknownCountryApiResponse: "nil"
          countries:
            - FR

    geoblock-only:
      chain:
        middlewares:
          - geoblock-france

    traefik-auth:
      basicAuth:
        usersFile: "/secrets/traefik_auth.htpasswd"
        realm: "Secure Area"
        removeHeader: true

    security-headers:
      headers:
        contentSecurityPolicy: >
          default-src 'self';
          style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com;
          font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com;
          img-src 'self' data: https://flagcdn.com;
        referrerPolicy: "no-referrer"
        permissionsPolicy: "geolocation=(), microphone=(), camera=(), payment=()"
        customResponseHeaders:
          X-Robots-Tag: "noindex, nofollow, nosnippet, noarchive"
        frameDeny: true
        browserXssFilter: true
        sslRedirect: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 63072000
        customFrameOptionsValue: "SAMEORIGIN"

    rate-limit:
      rateLimit:
        average: 20
        burst: 40

  services:
    dummy-error:
      loadBalancer:
        servers:
          - url: "http://web_app:5000"

tls:
  options:
    default:
      minVersion: VersionTLS13
      sniStrict: true
      cipherSuites:
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
